// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YSI.FeudalSword.Web.Database;

namespace YSI.FeudalSword.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DynastyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuzerainId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DynastyId");

                    b.HasIndex("SuzerainId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DynastyId = 1,
                            Name = "Джиор"
                        },
                        new
                        {
                            Id = 2,
                            DynastyId = 2,
                            Name = "Рикард"
                        },
                        new
                        {
                            Id = 3,
                            DynastyId = 3,
                            Name = "Эддард"
                        },
                        new
                        {
                            Id = 4,
                            DynastyId = 4,
                            Name = "Русе"
                        },
                        new
                        {
                            Id = 5,
                            DynastyId = 5,
                            Name = "Виллам"
                        },
                        new
                        {
                            Id = 6,
                            DynastyId = 6,
                            Name = "Виман"
                        },
                        new
                        {
                            Id = 7,
                            DynastyId = 7,
                            Name = "Мелдред"
                        },
                        new
                        {
                            Id = 8,
                            DynastyId = 8,
                            Name = "Родрик"
                        },
                        new
                        {
                            Id = 9,
                            DynastyId = 9,
                            Name = "Бейлон"
                        },
                        new
                        {
                            Id = 10,
                            DynastyId = 10,
                            Name = "Тристон"
                        },
                        new
                        {
                            Id = 11,
                            DynastyId = 11,
                            Name = "Роберт"
                        },
                        new
                        {
                            Id = 12,
                            DynastyId = 12,
                            Name = "Джон"
                        },
                        new
                        {
                            Id = 13,
                            DynastyId = 13,
                            Name = "Герольд"
                        },
                        new
                        {
                            Id = 14,
                            DynastyId = 14,
                            Name = "Уолдер"
                        },
                        new
                        {
                            Id = 15,
                            DynastyId = 15,
                            Name = "Хостер"
                        },
                        new
                        {
                            Id = 16,
                            DynastyId = 16,
                            Name = "Реймен"
                        },
                        new
                        {
                            Id = 17,
                            DynastyId = 17,
                            Name = "Клемент"
                        },
                        new
                        {
                            Id = 18,
                            DynastyId = 18,
                            Name = "Лео"
                        },
                        new
                        {
                            Id = 19,
                            DynastyId = 19,
                            Name = "Терренс"
                        },
                        new
                        {
                            Id = 20,
                            DynastyId = 20,
                            Name = "Андрос"
                        },
                        new
                        {
                            Id = 21,
                            DynastyId = 21,
                            Name = "Тайвин"
                        });
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        },
                        new
                        {
                            Id = 10
                        },
                        new
                        {
                            Id = 11
                        },
                        new
                        {
                            Id = 12
                        },
                        new
                        {
                            Id = 13
                        },
                        new
                        {
                            Id = 14
                        },
                        new
                        {
                            Id = 15
                        },
                        new
                        {
                            Id = 16
                        },
                        new
                        {
                            Id = 17
                        },
                        new
                        {
                            Id = 18
                        },
                        new
                        {
                            Id = 19
                        },
                        new
                        {
                            Id = 20
                        },
                        new
                        {
                            Id = 21
                        },
                        new
                        {
                            Id = 22
                        },
                        new
                        {
                            Id = 23
                        },
                        new
                        {
                            Id = 24
                        },
                        new
                        {
                            Id = 25
                        },
                        new
                        {
                            Id = 26
                        },
                        new
                        {
                            Id = 27
                        },
                        new
                        {
                            Id = 28
                        },
                        new
                        {
                            Id = 29
                        },
                        new
                        {
                            Id = 30
                        },
                        new
                        {
                            Id = 31
                        },
                        new
                        {
                            Id = 32
                        },
                        new
                        {
                            Id = 33
                        },
                        new
                        {
                            Id = 34
                        },
                        new
                        {
                            Id = 35
                        },
                        new
                        {
                            Id = 36
                        },
                        new
                        {
                            Id = 37
                        },
                        new
                        {
                            Id = 38
                        },
                        new
                        {
                            Id = 39
                        },
                        new
                        {
                            Id = 40
                        },
                        new
                        {
                            Id = 41
                        },
                        new
                        {
                            Id = 42
                        },
                        new
                        {
                            Id = 43
                        },
                        new
                        {
                            Id = 44
                        },
                        new
                        {
                            Id = 45
                        },
                        new
                        {
                            Id = 46
                        },
                        new
                        {
                            Id = 47
                        },
                        new
                        {
                            Id = 48
                        },
                        new
                        {
                            Id = 49
                        },
                        new
                        {
                            Id = 50
                        },
                        new
                        {
                            Id = 51
                        },
                        new
                        {
                            Id = 52
                        },
                        new
                        {
                            Id = 53
                        },
                        new
                        {
                            Id = 54
                        },
                        new
                        {
                            Id = 55
                        },
                        new
                        {
                            Id = 56
                        },
                        new
                        {
                            Id = 57
                        },
                        new
                        {
                            Id = 58
                        },
                        new
                        {
                            Id = 59
                        },
                        new
                        {
                            Id = 60
                        },
                        new
                        {
                            Id = 61
                        },
                        new
                        {
                            Id = 62
                        },
                        new
                        {
                            Id = 63
                        },
                        new
                        {
                            Id = 64
                        },
                        new
                        {
                            Id = 65
                        },
                        new
                        {
                            Id = 66
                        },
                        new
                        {
                            Id = 67
                        },
                        new
                        {
                            Id = 68
                        },
                        new
                        {
                            Id = 69
                        },
                        new
                        {
                            Id = 70
                        },
                        new
                        {
                            Id = 71
                        },
                        new
                        {
                            Id = 72
                        },
                        new
                        {
                            Id = 73
                        },
                        new
                        {
                            Id = 74
                        },
                        new
                        {
                            Id = 75
                        },
                        new
                        {
                            Id = 76
                        },
                        new
                        {
                            Id = 77
                        },
                        new
                        {
                            Id = 78
                        },
                        new
                        {
                            Id = 79
                        },
                        new
                        {
                            Id = 80
                        },
                        new
                        {
                            Id = 81
                        },
                        new
                        {
                            Id = 82
                        },
                        new
                        {
                            Id = 83
                        },
                        new
                        {
                            Id = 84
                        },
                        new
                        {
                            Id = 85
                        },
                        new
                        {
                            Id = 86
                        },
                        new
                        {
                            Id = 87
                        },
                        new
                        {
                            Id = 88
                        },
                        new
                        {
                            Id = 89
                        },
                        new
                        {
                            Id = 90
                        },
                        new
                        {
                            Id = 91
                        },
                        new
                        {
                            Id = 92
                        },
                        new
                        {
                            Id = 93
                        },
                        new
                        {
                            Id = 94
                        },
                        new
                        {
                            Id = 95
                        },
                        new
                        {
                            Id = 96
                        },
                        new
                        {
                            Id = 97
                        },
                        new
                        {
                            Id = 98
                        },
                        new
                        {
                            Id = 99
                        },
                        new
                        {
                            Id = 100
                        },
                        new
                        {
                            Id = 101
                        },
                        new
                        {
                            Id = 102
                        },
                        new
                        {
                            Id = 103
                        },
                        new
                        {
                            Id = 104
                        },
                        new
                        {
                            Id = 105
                        });
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Dynasty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dynasties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мормонт"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Карстарк"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Старк"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Болтон"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Дастин"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Мандерли"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Мерлин"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Харлоу"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Грейджой"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Сандерленд"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Аррен"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ройс"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Графтон"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Фрей"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Талли"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Дарри"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Пайпер"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Леффорд"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Кеннинг"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Бракс"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Ланнистер"
                        });
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CapitalId")
                        .HasColumnType("int");

                    b.Property<int?>("JureSuzerainId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JureSuzerainId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Rank");

                    b.HasIndex("CapitalId", "Rank");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapitalId = 1,
                            JureSuzerainId = 106,
                            Name = "Сумеречная башня",
                            OwnerId = 1,
                            Rank = 1
                        },
                        new
                        {
                            Id = 2,
                            CapitalId = 2,
                            JureSuzerainId = 106,
                            Name = "Чёрный замок",
                            OwnerId = 1,
                            Rank = 1
                        },
                        new
                        {
                            Id = 3,
                            CapitalId = 3,
                            JureSuzerainId = 106,
                            Name = "Восточный дозор",
                            OwnerId = 1,
                            Rank = 1
                        },
                        new
                        {
                            Id = 4,
                            CapitalId = 4,
                            JureSuzerainId = 106,
                            Name = "Новый дар",
                            OwnerId = 1,
                            Rank = 1
                        },
                        new
                        {
                            Id = 5,
                            CapitalId = 5,
                            JureSuzerainId = 107,
                            Name = "Скагос",
                            OwnerId = 2,
                            Rank = 1
                        },
                        new
                        {
                            Id = 6,
                            CapitalId = 6,
                            JureSuzerainId = 107,
                            Name = "Кархолд",
                            OwnerId = 2,
                            Rank = 1
                        },
                        new
                        {
                            Id = 7,
                            CapitalId = 7,
                            JureSuzerainId = 107,
                            Name = "Последний очаг",
                            OwnerId = 2,
                            Rank = 1
                        },
                        new
                        {
                            Id = 8,
                            CapitalId = 8,
                            JureSuzerainId = 107,
                            Name = "Вершина",
                            OwnerId = 2,
                            Rank = 1
                        },
                        new
                        {
                            Id = 9,
                            CapitalId = 9,
                            JureSuzerainId = 107,
                            Name = "Каменный холм",
                            OwnerId = 2,
                            Rank = 1
                        },
                        new
                        {
                            Id = 10,
                            CapitalId = 10,
                            JureSuzerainId = 108,
                            Name = "Медвежий остров",
                            OwnerId = 3,
                            Rank = 1
                        },
                        new
                        {
                            Id = 11,
                            CapitalId = 11,
                            JureSuzerainId = 108,
                            Name = "Мыс морского дракона",
                            OwnerId = 3,
                            Rank = 1
                        },
                        new
                        {
                            Id = 12,
                            CapitalId = 12,
                            JureSuzerainId = 108,
                            Name = "Темнолесье",
                            OwnerId = 3,
                            Rank = 1
                        },
                        new
                        {
                            Id = 13,
                            CapitalId = 13,
                            JureSuzerainId = 108,
                            Name = "Железный холм",
                            OwnerId = 3,
                            Rank = 1
                        },
                        new
                        {
                            Id = 14,
                            CapitalId = 14,
                            JureSuzerainId = 108,
                            Name = "Винтерфелл",
                            OwnerId = 3,
                            Rank = 1
                        },
                        new
                        {
                            Id = 15,
                            CapitalId = 15,
                            JureSuzerainId = 109,
                            Name = "Дредфорт",
                            OwnerId = 4,
                            Rank = 1
                        },
                        new
                        {
                            Id = 16,
                            CapitalId = 16,
                            JureSuzerainId = 109,
                            Name = "Вдовий дозор",
                            OwnerId = 4,
                            Rank = 1
                        },
                        new
                        {
                            Id = 17,
                            CapitalId = 17,
                            JureSuzerainId = 109,
                            Name = "Хорнвуд",
                            OwnerId = 4,
                            Rank = 1
                        },
                        new
                        {
                            Id = 18,
                            CapitalId = 18,
                            JureSuzerainId = 109,
                            Name = "Чёрная заводь",
                            OwnerId = 4,
                            Rank = 1
                        },
                        new
                        {
                            Id = 19,
                            CapitalId = 19,
                            JureSuzerainId = 109,
                            Name = "Замок Сервинов",
                            OwnerId = 4,
                            Rank = 1
                        },
                        new
                        {
                            Id = 20,
                            CapitalId = 20,
                            JureSuzerainId = 108,
                            Name = "Волчий лес",
                            OwnerId = 3,
                            Rank = 1
                        },
                        new
                        {
                            Id = 21,
                            CapitalId = 21,
                            JureSuzerainId = 110,
                            Name = "Торхенов удел",
                            OwnerId = 5,
                            Rank = 1
                        },
                        new
                        {
                            Id = 22,
                            CapitalId = 22,
                            JureSuzerainId = 110,
                            Name = "Каменный берег",
                            OwnerId = 5,
                            Rank = 1
                        },
                        new
                        {
                            Id = 23,
                            CapitalId = 23,
                            JureSuzerainId = 110,
                            Name = "Родники",
                            OwnerId = 5,
                            Rank = 1
                        },
                        new
                        {
                            Id = 24,
                            CapitalId = 24,
                            JureSuzerainId = 110,
                            Name = "Барроутон",
                            OwnerId = 5,
                            Rank = 1
                        },
                        new
                        {
                            Id = 25,
                            CapitalId = 25,
                            JureSuzerainId = 111,
                            Name = "Белая гавань",
                            OwnerId = 6,
                            Rank = 1
                        },
                        new
                        {
                            Id = 26,
                            CapitalId = 26,
                            JureSuzerainId = 111,
                            Name = "Бараньи ворота",
                            OwnerId = 6,
                            Rank = 1
                        },
                        new
                        {
                            Id = 27,
                            CapitalId = 27,
                            JureSuzerainId = 111,
                            Name = "Старый замок",
                            OwnerId = 6,
                            Rank = 1
                        },
                        new
                        {
                            Id = 28,
                            CapitalId = 28,
                            JureSuzerainId = 111,
                            Name = "Ров Кайлин",
                            OwnerId = 6,
                            Rank = 1
                        },
                        new
                        {
                            Id = 29,
                            CapitalId = 29,
                            JureSuzerainId = 111,
                            Name = "Перешеек",
                            OwnerId = 6,
                            Rank = 1
                        },
                        new
                        {
                            Id = 30,
                            CapitalId = 30,
                            JureSuzerainId = 110,
                            Name = "Кремневый палец",
                            OwnerId = 5,
                            Rank = 1
                        },
                        new
                        {
                            Id = 31,
                            CapitalId = 31,
                            JureSuzerainId = 112,
                            Name = "Чёрная волна",
                            OwnerId = 7,
                            Rank = 1
                        },
                        new
                        {
                            Id = 32,
                            CapitalId = 32,
                            JureSuzerainId = 112,
                            Name = "Старый Вик",
                            OwnerId = 7,
                            Rank = 1
                        },
                        new
                        {
                            Id = 33,
                            CapitalId = 33,
                            JureSuzerainId = 112,
                            Name = "Хаммерхорн",
                            OwnerId = 7,
                            Rank = 1
                        },
                        new
                        {
                            Id = 34,
                            CapitalId = 34,
                            JureSuzerainId = 112,
                            Name = "Одинокий светоч",
                            OwnerId = 7,
                            Rank = 1
                        },
                        new
                        {
                            Id = 35,
                            CapitalId = 35,
                            JureSuzerainId = 114,
                            Name = "Солёный утёс",
                            OwnerId = 9,
                            Rank = 1
                        },
                        new
                        {
                            Id = 36,
                            CapitalId = 36,
                            JureSuzerainId = 114,
                            Name = "Гольцы",
                            OwnerId = 9,
                            Rank = 1
                        },
                        new
                        {
                            Id = 37,
                            CapitalId = 37,
                            JureSuzerainId = 112,
                            Name = "Пебблтон",
                            OwnerId = 7,
                            Rank = 1
                        },
                        new
                        {
                            Id = 38,
                            CapitalId = 38,
                            JureSuzerainId = 113,
                            Name = "Оркмонт",
                            OwnerId = 8,
                            Rank = 1
                        },
                        new
                        {
                            Id = 39,
                            CapitalId = 39,
                            JureSuzerainId = 113,
                            Name = "Десять башен",
                            OwnerId = 8,
                            Rank = 1
                        },
                        new
                        {
                            Id = 40,
                            CapitalId = 40,
                            JureSuzerainId = 113,
                            Name = "Камнедрев",
                            OwnerId = 8,
                            Rank = 1
                        },
                        new
                        {
                            Id = 41,
                            CapitalId = 41,
                            JureSuzerainId = 114,
                            Name = "Железная роща",
                            OwnerId = 9,
                            Rank = 1
                        },
                        new
                        {
                            Id = 42,
                            CapitalId = 42,
                            JureSuzerainId = 114,
                            Name = "Лордпорт",
                            OwnerId = 9,
                            Rank = 1
                        },
                        new
                        {
                            Id = 43,
                            CapitalId = 43,
                            JureSuzerainId = 114,
                            Name = "Пайк",
                            OwnerId = 9,
                            Rank = 1
                        },
                        new
                        {
                            Id = 44,
                            CapitalId = 44,
                            JureSuzerainId = 113,
                            Name = "Волмарк",
                            OwnerId = 8,
                            Rank = 1
                        },
                        new
                        {
                            Id = 45,
                            CapitalId = 45,
                            JureSuzerainId = 115,
                            Name = "Длинная сестра",
                            OwnerId = 10,
                            Rank = 1
                        },
                        new
                        {
                            Id = 46,
                            CapitalId = 46,
                            JureSuzerainId = 115,
                            Name = "Милая сестра",
                            OwnerId = 10,
                            Rank = 1
                        },
                        new
                        {
                            Id = 47,
                            CapitalId = 47,
                            JureSuzerainId = 115,
                            Name = "Малая сестра",
                            OwnerId = 10,
                            Rank = 1
                        },
                        new
                        {
                            Id = 48,
                            CapitalId = 48,
                            JureSuzerainId = 115,
                            Name = "Галечный остров",
                            OwnerId = 10,
                            Rank = 1
                        },
                        new
                        {
                            Id = 49,
                            CapitalId = 49,
                            JureSuzerainId = 115,
                            Name = "Сосцы",
                            OwnerId = 10,
                            Rank = 1
                        },
                        new
                        {
                            Id = 50,
                            CapitalId = 50,
                            JureSuzerainId = 116,
                            Name = "Персты",
                            OwnerId = 11,
                            Rank = 1
                        },
                        new
                        {
                            Id = 51,
                            CapitalId = 51,
                            JureSuzerainId = 116,
                            Name = "Ледяной ручей",
                            OwnerId = 11,
                            Rank = 1
                        },
                        new
                        {
                            Id = 52,
                            CapitalId = 52,
                            JureSuzerainId = 116,
                            Name = "Суровая песнь",
                            OwnerId = 11,
                            Rank = 1
                        },
                        new
                        {
                            Id = 53,
                            CapitalId = 53,
                            JureSuzerainId = 116,
                            Name = "Змеиный лес",
                            OwnerId = 11,
                            Rank = 1
                        },
                        new
                        {
                            Id = 54,
                            CapitalId = 54,
                            JureSuzerainId = 117,
                            Name = "Дом сердец",
                            OwnerId = 12,
                            Rank = 1
                        },
                        new
                        {
                            Id = 55,
                            CapitalId = 55,
                            JureSuzerainId = 117,
                            Name = "Длинный лук",
                            OwnerId = 12,
                            Rank = 1
                        },
                        new
                        {
                            Id = 56,
                            CapitalId = 56,
                            JureSuzerainId = 117,
                            Name = "Старый якорь",
                            OwnerId = 12,
                            Rank = 1
                        },
                        new
                        {
                            Id = 57,
                            CapitalId = 57,
                            JureSuzerainId = 117,
                            Name = "Девять звёзд",
                            OwnerId = 12,
                            Rank = 1
                        },
                        new
                        {
                            Id = 58,
                            CapitalId = 58,
                            JureSuzerainId = 117,
                            Name = "Железная дубрава",
                            OwnerId = 12,
                            Rank = 1
                        },
                        new
                        {
                            Id = 59,
                            CapitalId = 59,
                            JureSuzerainId = 116,
                            Name = "Орлиное гнездо",
                            OwnerId = 11,
                            Rank = 1
                        },
                        new
                        {
                            Id = 60,
                            CapitalId = 60,
                            JureSuzerainId = 118,
                            Name = "Редфорт",
                            OwnerId = 13,
                            Rank = 1
                        },
                        new
                        {
                            Id = 61,
                            CapitalId = 61,
                            JureSuzerainId = 118,
                            Name = "Серая лощина",
                            OwnerId = 13,
                            Rank = 1
                        },
                        new
                        {
                            Id = 62,
                            CapitalId = 62,
                            JureSuzerainId = 117,
                            Name = "Рунный камень",
                            OwnerId = 12,
                            Rank = 1
                        },
                        new
                        {
                            Id = 63,
                            CapitalId = 63,
                            JureSuzerainId = 118,
                            Name = "Ведьмин остров",
                            OwnerId = 13,
                            Rank = 1
                        },
                        new
                        {
                            Id = 64,
                            CapitalId = 64,
                            JureSuzerainId = 118,
                            Name = "Чаячий город",
                            OwnerId = 13,
                            Rank = 1
                        },
                        new
                        {
                            Id = 65,
                            CapitalId = 65,
                            JureSuzerainId = 118,
                            Name = "Фитили",
                            OwnerId = 13,
                            Rank = 1
                        },
                        new
                        {
                            Id = 66,
                            CapitalId = 66,
                            JureSuzerainId = 119,
                            Name = "Близнецы",
                            OwnerId = 14,
                            Rank = 1
                        },
                        new
                        {
                            Id = 67,
                            CapitalId = 67,
                            JureSuzerainId = 119,
                            Name = "Сигард",
                            OwnerId = 14,
                            Rank = 1
                        },
                        new
                        {
                            Id = 68,
                            CapitalId = 68,
                            JureSuzerainId = 119,
                            Name = "Старые камни",
                            OwnerId = 14,
                            Rank = 1
                        },
                        new
                        {
                            Id = 69,
                            CapitalId = 69,
                            JureSuzerainId = 119,
                            Name = "Добрая ярмарка",
                            OwnerId = 14,
                            Rank = 1
                        },
                        new
                        {
                            Id = 70,
                            CapitalId = 70,
                            JureSuzerainId = 119,
                            Name = "Вранодрев",
                            OwnerId = 14,
                            Rank = 1
                        },
                        new
                        {
                            Id = 71,
                            CapitalId = 71,
                            JureSuzerainId = 120,
                            Name = "Риверран",
                            OwnerId = 15,
                            Rank = 1
                        },
                        new
                        {
                            Id = 72,
                            CapitalId = 72,
                            JureSuzerainId = 120,
                            Name = "Каменный оплот",
                            OwnerId = 15,
                            Rank = 1
                        },
                        new
                        {
                            Id = 73,
                            CapitalId = 73,
                            JureSuzerainId = 120,
                            Name = "Замок Личестеров",
                            OwnerId = 15,
                            Rank = 1
                        },
                        new
                        {
                            Id = 74,
                            CapitalId = 74,
                            JureSuzerainId = 120,
                            Name = "Город Харровея",
                            OwnerId = 15,
                            Rank = 1
                        },
                        new
                        {
                            Id = 75,
                            CapitalId = 75,
                            JureSuzerainId = 121,
                            Name = "Дарри",
                            OwnerId = 16,
                            Rank = 1
                        },
                        new
                        {
                            Id = 76,
                            CapitalId = 76,
                            JureSuzerainId = 121,
                            Name = "Солеварни",
                            OwnerId = 16,
                            Rank = 1
                        },
                        new
                        {
                            Id = 77,
                            CapitalId = 77,
                            JureSuzerainId = 121,
                            Name = "Девичий пруд",
                            OwnerId = 16,
                            Rank = 1
                        },
                        new
                        {
                            Id = 78,
                            CapitalId = 78,
                            JureSuzerainId = 121,
                            Name = "Харренхол",
                            OwnerId = 16,
                            Rank = 1
                        },
                        new
                        {
                            Id = 79,
                            CapitalId = 79,
                            JureSuzerainId = 121,
                            Name = "Жёлудь",
                            OwnerId = 16,
                            Rank = 1
                        },
                        new
                        {
                            Id = 80,
                            CapitalId = 80,
                            JureSuzerainId = 120,
                            Name = "Атранта",
                            OwnerId = 15,
                            Rank = 1
                        },
                        new
                        {
                            Id = 81,
                            CapitalId = 81,
                            JureSuzerainId = 122,
                            Name = "Розовая дева",
                            OwnerId = 17,
                            Rank = 1
                        },
                        new
                        {
                            Id = 82,
                            CapitalId = 82,
                            JureSuzerainId = 122,
                            Name = "Приют странника",
                            OwnerId = 17,
                            Rank = 1
                        },
                        new
                        {
                            Id = 83,
                            CapitalId = 83,
                            JureSuzerainId = 122,
                            Name = "Каслвуд",
                            OwnerId = 17,
                            Rank = 1
                        },
                        new
                        {
                            Id = 84,
                            CapitalId = 84,
                            JureSuzerainId = 122,
                            Name = "Каменная септа",
                            OwnerId = 17,
                            Rank = 1
                        },
                        new
                        {
                            Id = 85,
                            CapitalId = 85,
                            JureSuzerainId = 123,
                            Name = "Виндхолл",
                            OwnerId = 18,
                            Rank = 1
                        },
                        new
                        {
                            Id = 86,
                            CapitalId = 86,
                            JureSuzerainId = 123,
                            Name = "Гибельная крепость",
                            OwnerId = 18,
                            Rank = 1
                        },
                        new
                        {
                            Id = 87,
                            CapitalId = 87,
                            JureSuzerainId = 123,
                            Name = "Скала",
                            OwnerId = 18,
                            Rank = 1
                        },
                        new
                        {
                            Id = 88,
                            CapitalId = 88,
                            JureSuzerainId = 123,
                            Name = "Кастамере",
                            OwnerId = 18,
                            Rank = 1
                        },
                        new
                        {
                            Id = 89,
                            CapitalId = 89,
                            JureSuzerainId = 123,
                            Name = "Золотой зуб",
                            OwnerId = 18,
                            Rank = 1
                        },
                        new
                        {
                            Id = 90,
                            CapitalId = 90,
                            JureSuzerainId = 124,
                            Name = "Эшмарк",
                            OwnerId = 19,
                            Rank = 1
                        },
                        new
                        {
                            Id = 91,
                            CapitalId = 91,
                            JureSuzerainId = 124,
                            Name = "Тарбекхолл",
                            OwnerId = 19,
                            Rank = 1
                        },
                        new
                        {
                            Id = 92,
                            CapitalId = 92,
                            JureSuzerainId = 124,
                            Name = "Светлый остров",
                            OwnerId = 19,
                            Rank = 1
                        },
                        new
                        {
                            Id = 93,
                            CapitalId = 93,
                            JureSuzerainId = 124,
                            Name = "Пиршественные огни",
                            OwnerId = 19,
                            Rank = 1
                        },
                        new
                        {
                            Id = 94,
                            CapitalId = 94,
                            JureSuzerainId = 124,
                            Name = "Сарсфилд",
                            OwnerId = 19,
                            Rank = 1
                        },
                        new
                        {
                            Id = 95,
                            CapitalId = 95,
                            JureSuzerainId = 125,
                            Name = "Хорнваль",
                            OwnerId = 20,
                            Rank = 1
                        },
                        new
                        {
                            Id = 96,
                            CapitalId = 96,
                            JureSuzerainId = 125,
                            Name = "Глубокая нора",
                            OwnerId = 20,
                            Rank = 1
                        },
                        new
                        {
                            Id = 97,
                            CapitalId = 97,
                            JureSuzerainId = 125,
                            Name = "Ключи",
                            OwnerId = 20,
                            Rank = 1
                        },
                        new
                        {
                            Id = 98,
                            CapitalId = 98,
                            JureSuzerainId = 125,
                            Name = "Серебрянный холм",
                            OwnerId = 20,
                            Rank = 1
                        },
                        new
                        {
                            Id = 99,
                            CapitalId = 99,
                            JureSuzerainId = 126,
                            Name = "Замок Клиганов",
                            OwnerId = 21,
                            Rank = 1
                        },
                        new
                        {
                            Id = 100,
                            CapitalId = 100,
                            JureSuzerainId = 126,
                            Name = "Утёс Кастерли",
                            OwnerId = 21,
                            Rank = 1
                        },
                        new
                        {
                            Id = 101,
                            CapitalId = 101,
                            JureSuzerainId = 126,
                            Name = "Ланниспорт",
                            OwnerId = 21,
                            Rank = 1
                        },
                        new
                        {
                            Id = 102,
                            CapitalId = 102,
                            JureSuzerainId = 126,
                            Name = "Крейкхолл",
                            OwnerId = 21,
                            Rank = 1
                        },
                        new
                        {
                            Id = 103,
                            CapitalId = 103,
                            JureSuzerainId = 126,
                            Name = "Корнфилд",
                            OwnerId = 21,
                            Rank = 1
                        },
                        new
                        {
                            Id = 104,
                            CapitalId = 104,
                            JureSuzerainId = 126,
                            Name = "Гринфилд",
                            OwnerId = 21,
                            Rank = 1
                        },
                        new
                        {
                            Id = 105,
                            CapitalId = 105,
                            JureSuzerainId = 125,
                            Name = "Золотая дорога",
                            OwnerId = 20,
                            Rank = 1
                        },
                        new
                        {
                            Id = 106,
                            CapitalId = 2,
                            JureSuzerainId = 127,
                            Name = "Ночной дозор",
                            Rank = 2
                        },
                        new
                        {
                            Id = 107,
                            CapitalId = 6,
                            JureSuzerainId = 127,
                            Name = "Тюлений залив",
                            Rank = 2
                        },
                        new
                        {
                            Id = 108,
                            CapitalId = 14,
                            JureSuzerainId = 127,
                            Name = "Винтерфелл",
                            Rank = 2
                        },
                        new
                        {
                            Id = 109,
                            CapitalId = 15,
                            JureSuzerainId = 127,
                            Name = "Бараньи Лбы",
                            Rank = 2
                        },
                        new
                        {
                            Id = 110,
                            CapitalId = 24,
                            JureSuzerainId = 127,
                            Name = "Блистающий залив",
                            Rank = 2
                        },
                        new
                        {
                            Id = 111,
                            CapitalId = 25,
                            JureSuzerainId = 127,
                            Name = "Пасть",
                            Rank = 2
                        },
                        new
                        {
                            Id = 112,
                            CapitalId = 37,
                            JureSuzerainId = 128,
                            Name = "Острова Вика",
                            Rank = 2
                        },
                        new
                        {
                            Id = 113,
                            CapitalId = 39,
                            JureSuzerainId = 128,
                            Name = "Остров Харлоу",
                            Rank = 2
                        },
                        new
                        {
                            Id = 114,
                            CapitalId = 43,
                            JureSuzerainId = 128,
                            Name = "Остров Пайк",
                            Rank = 2
                        },
                        new
                        {
                            Id = 115,
                            CapitalId = 46,
                            JureSuzerainId = 129,
                            Name = "Три Сестры",
                            Rank = 2
                        },
                        new
                        {
                            Id = 116,
                            CapitalId = 59,
                            JureSuzerainId = 129,
                            Name = "Лунные горы",
                            Rank = 2
                        },
                        new
                        {
                            Id = 117,
                            CapitalId = 62,
                            JureSuzerainId = 129,
                            Name = "Доллина",
                            Rank = 2
                        },
                        new
                        {
                            Id = 118,
                            CapitalId = 64,
                            JureSuzerainId = 129,
                            Name = "Крабий залив",
                            Rank = 2
                        },
                        new
                        {
                            Id = 119,
                            CapitalId = 66,
                            JureSuzerainId = 130,
                            Name = "Северные зубцы",
                            Rank = 2
                        },
                        new
                        {
                            Id = 120,
                            CapitalId = 71,
                            JureSuzerainId = 130,
                            Name = "Красный зубец",
                            Rank = 2
                        },
                        new
                        {
                            Id = 121,
                            CapitalId = 75,
                            JureSuzerainId = 130,
                            Name = "Трезубец",
                            Rank = 2
                        },
                        new
                        {
                            Id = 122,
                            CapitalId = 81,
                            JureSuzerainId = 130,
                            Name = "Водопад",
                            Rank = 2
                        },
                        new
                        {
                            Id = 123,
                            CapitalId = 89,
                            JureSuzerainId = 131,
                            Name = "Холмы Пендрика",
                            Rank = 2
                        },
                        new
                        {
                            Id = 124,
                            CapitalId = 93,
                            JureSuzerainId = 131,
                            Name = "Кайс",
                            Rank = 2
                        },
                        new
                        {
                            Id = 125,
                            CapitalId = 95,
                            JureSuzerainId = 131,
                            Name = "Западные Холмы",
                            Rank = 2
                        },
                        new
                        {
                            Id = 126,
                            CapitalId = 100,
                            JureSuzerainId = 131,
                            Name = "Золотой залив",
                            Rank = 2
                        },
                        new
                        {
                            Id = 127,
                            CapitalId = 14,
                            JureSuzerainId = 132,
                            Name = "Север",
                            Rank = 3
                        },
                        new
                        {
                            Id = 128,
                            CapitalId = 43,
                            JureSuzerainId = 132,
                            Name = "Железные острова",
                            Rank = 3
                        },
                        new
                        {
                            Id = 129,
                            CapitalId = 59,
                            JureSuzerainId = 132,
                            Name = "Доллина Аррен",
                            Rank = 3
                        },
                        new
                        {
                            Id = 130,
                            CapitalId = 71,
                            JureSuzerainId = 132,
                            Name = "Речные земли",
                            Rank = 3
                        },
                        new
                        {
                            Id = 131,
                            CapitalId = 100,
                            JureSuzerainId = 132,
                            Name = "Запад",
                            Rank = 3
                        },
                        new
                        {
                            Id = 132,
                            CapitalId = 71,
                            Name = "Семь Королевст",
                            Rank = 4
                        });
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LastActivity");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("YSI.FeudalSword.Web.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("YSI.FeudalSword.Web.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YSI.FeudalSword.Web.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("YSI.FeudalSword.Web.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Character", b =>
                {
                    b.HasOne("YSI.FeudalSword.Web.Database.Models.Dynasty", "Dynasty")
                        .WithMany("Characters")
                        .HasForeignKey("DynastyId");

                    b.HasOne("YSI.FeudalSword.Web.Database.Models.Character", "Suzerain")
                        .WithMany("Vassals")
                        .HasForeignKey("SuzerainId");

                    b.HasOne("YSI.FeudalSword.Web.Database.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId");

                    b.Navigation("Dynasty");

                    b.Navigation("Suzerain");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Title", b =>
                {
                    b.HasOne("YSI.FeudalSword.Web.Database.Models.Domain", "Capital")
                        .WithMany("Titles")
                        .HasForeignKey("CapitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YSI.FeudalSword.Web.Database.Models.Title", "JureSuzerain")
                        .WithMany("JureVassals")
                        .HasForeignKey("JureSuzerainId");

                    b.HasOne("YSI.FeudalSword.Web.Database.Models.Character", "Owner")
                        .WithMany("Titles")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Capital");

                    b.Navigation("JureSuzerain");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Character", b =>
                {
                    b.Navigation("Titles");

                    b.Navigation("Vassals");
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Domain", b =>
                {
                    b.Navigation("Titles");
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Dynasty", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.Title", b =>
                {
                    b.Navigation("JureVassals");
                });

            modelBuilder.Entity("YSI.FeudalSword.Web.Database.Models.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
